"""initial schema

Revision ID: 42d39aa9055a
Revises: 
Create Date: 2026-09-01 17:20:26.654444

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '42d39aa9055a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rate_limits',
    sa.Column('bucket_hash', sa.String(length=64), nullable=False),
    sa.Column('window_start', sa.BigInteger(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('bucket_hash', 'window_start')
    )
    op.create_index(op.f('ix_rate_limits_expires_at'), 'rate_limits', ['expires_at'], unique=False)
    op.create_table('records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('blind_index', sa.String(length=64), nullable=False),
    sa.Column('sealed', sa.Text(), nullable=False),
    sa.Column('bytes', sa.Integer(), nullable=False),
    sa.Column('stored_at', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('blind_index')
    )
    op.create_table('server_sessions',
    sa.Column('session_id_hash', sa.String(length=64), nullable=False),
    sa.Column('csrf_token', sa.Text(), nullable=False),
    sa.Column('identity_id', sa.Integer(), nullable=True),
    sa.Column('authenticated_at', sa.Double(), nullable=True),
    sa.Column('vault_unlocked', sa.Boolean(), nullable=False),
    sa.Column('active_ceremony_id', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Double(), nullable=False),
    sa.Column('last_seen_at', sa.Double(), nullable=False),
    sa.Column('expires_at', sa.Double(), nullable=False),
    sa.Column('revoked_at', sa.Double(), nullable=True),
    sa.PrimaryKeyConstraint('session_id_hash')
    )
    op.create_index(op.f('ix_server_sessions_expires_at'), 'server_sessions', ['expires_at'], unique=False)
    op.create_table('vault_identity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_handle', sa.LargeBinary(), nullable=False),
    sa.Column('passkey_required', sa.Boolean(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('id = 1', name='ck_vault_identity_singleton'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_handle')
    )
    op.create_table('audit_events',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('occurred_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('event_type', sa.Enum('PASSKEY_REGISTERED', 'PASSKEY_REMOVED', 'PASSKEY_AUTH_SUCCESS', 'PASSKEY_AUTH_FAILURE', 'PASSKEY_PROTECTION_DISABLED', 'SESSION_REVOKED', 'SUSPICIOUS_COUNTER_EVENT', name='audit_event_type', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('identity_id', sa.Integer(), nullable=True),
    sa.Column('client_ref', sa.String(length=12), nullable=False),
    sa.Column('credential_id', sa.LargeBinary(), nullable=True),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['identity_id'], ['vault_identity.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_events_event_type'), 'audit_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_audit_events_occurred_at'), 'audit_events', ['occurred_at'], unique=False)
    op.create_table('passkey_credentials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('identity_id', sa.Integer(), nullable=False),
    sa.Column('credential_id', sa.LargeBinary(), nullable=False),
    sa.Column('credential_public_key', sa.LargeBinary(), nullable=False),
    sa.Column('sign_count', sa.BigInteger(), nullable=False),
    sa.Column('transports', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('device_type', sa.Text(), nullable=True),
    sa.Column('backed_up', sa.Boolean(), nullable=True),
    sa.Column('label', sa.String(length=80), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_used_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['identity_id'], ['vault_identity.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('credential_id')
    )
    op.create_table('webauthn_challenges',
    sa.Column('ceremony_id', sa.Text(), nullable=False),
    sa.Column('session_id_hash', sa.String(length=64), nullable=False),
    sa.Column('identity_id', sa.Integer(), nullable=True),
    sa.Column('kind', sa.Enum('registration', 'authentication', name='webauthn_ceremony_kind', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('challenge', sa.LargeBinary(), nullable=False),
    sa.Column('created_at', sa.Double(), nullable=False),
    sa.Column('expires_at', sa.Double(), nullable=False),
    sa.Column('consumed_at', sa.Double(), nullable=True),
    sa.ForeignKeyConstraint(['session_id_hash'], ['server_sessions.session_id_hash'], ),
    sa.PrimaryKeyConstraint('ceremony_id')
    )
    op.create_index(op.f('ix_webauthn_challenges_session_id_hash'), 'webauthn_challenges', ['session_id_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_webauthn_challenges_session_id_hash'), table_name='webauthn_challenges')
    op.drop_table('webauthn_challenges')
    op.drop_table('passkey_credentials')
    op.drop_index(op.f('ix_audit_events_occurred_at'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_event_type'), table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_table('vault_identity')
    op.drop_index(op.f('ix_server_sessions_expires_at'), table_name='server_sessions')
    op.drop_table('server_sessions')
    op.drop_table('records')
    op.drop_index(op.f('ix_rate_limits_expires_at'), table_name='rate_limits')
    op.drop_table('rate_limits')
    # ### end Alembic commands ###
